name: save
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  image_picker: ^1.0.4
  firebase_storage: ^11.5.1
  intl: ^0.18.1
  svg_flutter: ^0.0.1
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.6
  flick_video_player: ^0.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/photos/
    - assets/icons/
    - assets/logo/
    - assets/eye/
    - assets/leg/
    - assets/background/