// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdwH-yXHZRdk213U6YBbiuYF--mJx5uNk',
    appId: '1:365045101497:web:5d730adf20147e0f387c68',
    messagingSenderId: '365045101497',
    projectId: 'paws-55b76',
    authDomain: 'paws-55b76.firebaseapp.com',
    storageBucket: 'paws-55b76.appspot.com',
    measurementId: 'G-T8R442J1EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CfiWfl1Dypmvr3lu79LDyQUmUnGvH4k',
    appId: '1:938042814633:android:20bf9d1e9df8bdaa8079b8',
    messagingSenderId: '938042814633',
    projectId: 'paws-2c3ea',
    storageBucket: 'paws-2c3ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19fm5uwAaGPln9J37a60SV0Yy_twJ1mU',
    appId: '1:365045101497:ios:04a1ea7c79aadf5c387c68',
    messagingSenderId: '365045101497',
    projectId: 'paws-55b76',
    storageBucket: 'paws-55b76.appspot.com',
    iosBundleId: 'com.example.save',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD19fm5uwAaGPln9J37a60SV0Yy_twJ1mU',
    appId: '1:365045101497:ios:91957ceab7f2f870387c68',
    messagingSenderId: '365045101497',
    projectId: 'paws-55b76',
    storageBucket: 'paws-55b76.appspot.com',
    iosBundleId: 'com.example.save.RunnerTests',
  );
}
